linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/opd-ai/go-ratox
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - asciicheck
  # - deadcode        (replaced by unused)
  # - depguard        (config not applicable to this project)
  # - exportloopref   (replaced by copyloopvar; redundant since Go 1.22)
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - golint          (replaced by revive)
  # - gomnd           (replaced by mnd)
  # - interfacer      (archived)
  # - maligned
  # - nestif
  # - prealloc
  # - scopelint       (replaced by copyloopvar)
  # - structcheck     (replaced by unused)
  # - testpackage
  # - varcheck        (replaced by unused)
  # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

  exclude-files:
    - ".*\\.pb\\.go$"

run:
  timeout: 5m
  exclude-dirs:
    - build
    - vendor
